/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllOfMatches: typeof import('./components/blocks/AllOfMatches.vue')['default']
    AuthCodeModal: typeof import('./components/layout/AuthCodeModal.vue')['default']
    FAQ: typeof import('./components/blocks/FAQ.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    HeroBlock: typeof import('./components/blocks/HeroBlock.vue')['default']
    HowItWork: typeof import('./components/blocks/HowItWork.vue')['default']
    IsLoading: typeof import('./components/ui/IsLoading.vue')['default']
    IsLoadingBalls: typeof import('./components/ui/IsLoadingBalls.vue')['default']
    MainPrize: typeof import('./components/blocks/MainPrize.vue')['default']
    MatchCard: typeof import('./components/layout/MatchCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
